import { Category, TeamMember, Ticket, LineSettings, SupabaseConfig } from '../types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat-network',
    name: 'ปัญหาอินเทอร์เน็ตและเครือข่าย',
    description: 'เชื่อมต่อ Wi-Fi ไม่ได้, สาย LAN หลุด, ความเร็วช้า หรือเข้าเว็บไม่ได้',
    color: 'emerald',
    icon: 'Wifi',
    isActive: true,
  },
  {
    id: 'cat-hardware',
    name: 'อุปกรณ์และคอมพิวเตอร์ชำรุด',
    description: 'คอมพิวเตอร์เปิดไม่ติด, จอดำ, ปริ้นเตอร์ไม่ทำงาน หรืออุปกรณ์ต่อพ่วงมีปัญหา',
    color: 'blue',
    icon: 'Monitor',
    isActive: true,
  },
  {
    id: 'cat-software',
    name: 'ระบบโปรแกรมและซอฟต์แวร์',
    description: 'โปรแกรมค้าง, แจ้ง Error, อัปเดตไม่ผ่าน, ฐานข้อมูลขัดข้อง',
    color: 'purple',
    icon: 'Laptop',
    isActive: true,
  },
  {
    id: 'cat-account',
    name: 'บัญชีผู้ใช้และสิทธิ์การเข้าถึง',
    description: 'ลืมรหัสผ่าน, เข้าสู่ระบบไม่ได้, ขอเพิ่มสิทธิ์ หรือสร้างบัญชีใหม่',
    color: 'amber',
    icon: 'Key',
    isActive: true,
  },
  {
    id: 'cat-other',
    name: 'สอบถามข้อมูลและบริการทั่วไป',
    description: 'ขอคำปรึกษาการใช้งาน หรือเรื่องอื่นๆ ที่ไม่ระบุไว้ข้างต้น',
    color: 'slate',
    icon: 'HelpCircle',
    isActive: true,
  },
];

export const INITIAL_TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'tm-1',
    name: 'วิชาญ ชัยมงคล (ช่างวิชาญ)',
    role: 'Senior IT Support Lead',
    lineId: '@wichan_it',
    phone: '081-456-7890',
    email: 'wichan@helpdesk.local',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    specialty: 'ระบบเครือข่าย, เซิร์ฟเวอร์ และฮาร์ดแวร์แม่ข่าย',
  },
  {
    id: 'tm-2',
    name: 'กานดา สุขสมบูรณ์ (ช่างกาน)',
    role: 'IT Application Specialist',
    lineId: '@kanda_dev',
    phone: '089-123-4567',
    email: 'kanda@helpdesk.local',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    specialty: 'ซอฟต์แวร์, ฐานข้อมูล และระบบสิทธิ์เข้าถึง',
  },
  {
    id: 'tm-3',
    name: 'ธีรเดช พัฒนไพบูลย์ (ช่างเดช)',
    role: 'On-site Technician & Hardware',
    lineId: '@theeradech_tech',
    phone: '086-789-0123',
    email: 'theeradech@helpdesk.local',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    specialty: 'คอมพิวเตอร์ตั้งโต๊ะ, จอภาพ, เครื่องพิมพ์, สายสัญญาณ',
  },
];

export const INITIAL_TICKETS: Ticket[] = [
  {
    id: 'TK-2610-001',
    reporterName: 'กิตติศักดิ์ เจริญพร',
    categoryId: 'cat-network',
    categoryName: 'ปัญหาอินเทอร์เน็ตและเครือข่าย',
    description: 'Wi-Fi ชั้น 3 แผนกบัญชีหลุดบ่อยมาก เชื่อมต่อแล้วขึ้น No Internet ทำงานส่งยอดไม่ได้ครับ',
    priority: 'urgent_highest',
    images: ['https://images.unsplash.com/photo-1544197150-b99a580bb7a8?w=800&auto=format&fit=crop&q=80'],
    lineContact: 'kittisak.line',
    phone: '081-111-2233',
    status: 'in_progress',
    assignedTo: 'tm-1',
    assignedMemberName: 'วิชาญ ชัยมงคล (ช่างวิชาญ)',
    createdAt: '2026-10-05T08:30:00.000Z',
    updatedAt: '2026-10-05T10:15:00.000Z',
    timeline: [
      {
        id: 'tl-1',
        status: 'pending',
        note: 'ลูกค้าเปิดเคสผ่านเว็บไซต์ ส่งแจ้งเตือนเข้า LINE เจ้าหน้าที่เรียบร้อย',
        updatedBy: 'ระบบอัตโนมัติ',
        timestamp: '2026-10-05T08:30:00.000Z',
      },
      {
        id: 'tl-2',
        status: 'investigating',
        note: 'ช่างวิชาญรับเคส ตรวจสอบสัญญาณ Access Point ชั้น 3 พบ Packet drop สูง',
        updatedBy: 'วิชาญ ชัยมงคล',
        timestamp: '2026-10-05T09:00:00.000Z',
      },
      {
        id: 'tl-3',
        status: 'in_progress',
        note: 'กำลังรีบูต Switch PoE ประจำชั้น และปรับ Channel สัญญาณเพื่อลดสัญญาณกวน',
        updatedBy: 'วิชาญ ชัยมงคล',
        timestamp: '2026-10-05T10:15:00.000Z',
      },
    ],
  },
  {
    id: 'TK-2610-002',
    reporterName: 'สุจิตรา วงศ์สวัสดิ์',
    categoryId: 'cat-software',
    categoryName: 'ระบบโปรแกรมและซอฟต์แวร์',
    description: 'เปิดโปรแกรมจัดทำใบเสร็จแล้วค้าง Error 502 Bad Gateway ออกเอกสารให้ลูกค้าหน้าร้านไม่ได้',
    priority: 'urgent',
    images: ['https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80'],
    lineContact: 'sujitra_acc',
    phone: '082-333-4455',
    status: 'waiting_verification',
    assignedTo: 'tm-2',
    assignedMemberName: 'กานดา สุขสมบูรณ์ (ช่างกาน)',
    createdAt: '2026-10-05T09:10:00.000Z',
    updatedAt: '2026-10-05T11:40:00.000Z',
    solutionNotes: 'รีสตาร์ต API service ของระบบใบเสร็จ และเคลียร์ cache เรียบร้อยแล้ว แจ้งลูกค้าให้ทดลองเข้าใช้งาน',
    timeline: [
      {
        id: 'tl-4',
        status: 'pending',
        note: 'แจ้งเคสเข้าระบบ',
        updatedBy: 'สุจิตรา วงศ์สวัสดิ์',
        timestamp: '2026-10-05T09:10:00.000Z',
      },
      {
        id: 'tl-5',
        status: 'in_progress',
        note: 'ช่างกานดา เข้าตรวจสอบ Log เซิร์ฟเวอร์ พบ Thread ค้าง',
        updatedBy: 'กานดา สุขสมบูรณ์',
        timestamp: '2026-10-05T09:45:00.000Z',
      },
      {
        id: 'tl-6',
        status: 'waiting_verification',
        note: 'แก้ไขบริการเรียบร้อย ส่งข้อความแจ้งให้ผู้ใช้ทดสอบพิมพ์ใบเสร็จ',
        updatedBy: 'กานดา สุขสมบูรณ์',
        timestamp: '2026-10-05T11:40:00.000Z',
      },
    ],
  },
  {
    id: 'TK-2610-003',
    reporterName: 'ธวัชชัย รัตนประเสริฐ',
    categoryId: 'cat-hardware',
    categoryName: 'อุปกรณ์และคอมพิวเตอร์ชำรุด',
    description: 'เครื่องพิมพ์เลเซอร์ HP ชั้น 2 กระดาษติดและมีควันกลิ่นไหม้ออกมาจากถาดความร้อน',
    priority: 'urgent_highest',
    images: [],
    lineContact: 'thawatchai_r',
    phone: '085-555-6677',
    status: 'resolved',
    assignedTo: 'tm-3',
    assignedMemberName: 'ธีรเดช พัฒนไพบูลย์ (ช่างเดช)',
    createdAt: '2026-10-04T13:20:00.000Z',
    updatedAt: '2026-10-04T15:30:00.000Z',
    resolvedAt: '2026-10-04T15:30:00.000Z',
    solutionNotes: 'ถอดชุด Fuser ออก พบเศษพลาสติกติดขัด ทำความสะอาดและเปลี่ยนลูกกลิ้งใหม่ ทดสอบพิมพ์ 50 แผ่นราบรื่น',
    rating: 5,
    customerFeedback: 'ช่างมาไวมาก แก้ปัญหาเสร็จทันใจ สุภาพมากครับ',
    timeline: [
      {
        id: 'tl-7',
        status: 'pending',
        note: 'รับแจ้งเคสด่วนที่สุด',
        updatedBy: 'ระบบอัตโนมัติ',
        timestamp: '2026-10-04T13:20:00.000Z',
      },
      {
        id: 'tl-8',
        status: 'in_progress',
        note: 'ช่างเดชเดินทางไปตรวจเครื่องพิมพ์ที่ชั้น 2 ปิดสวิตช์และถอดปลั๊กทันที',
        updatedBy: 'ธีรเดช พัฒนไพบูลย์',
        timestamp: '2026-10-04T13:40:00.000Z',
      },
      {
        id: 'tl-9',
        status: 'resolved',
        note: 'เปลี่ยนอะไหล่ชุดความร้อน ทดสอบพิมพ์สำเร็จ ส่งมอบงาน',
        updatedBy: 'ธีรเดช พัฒนไพบูลย์',
        timestamp: '2026-10-04T15:30:00.000Z',
      },
    ],
  },
  {
    id: 'TK-2610-004',
    reporterName: 'พิมพา นวรัตน์',
    categoryId: 'cat-account',
    categoryName: 'บัญชีผู้ใช้และสิทธิ์การเข้าถึง',
    description: 'ต้องการรีเซ็ตรหัสผ่านอีเมลองค์กร และขอสิทธิ์เข้าใช้งานโฟลเดอร์แชร์งานฝ่ายการตลาด',
    priority: 'normal',
    images: [],
    lineContact: 'pimpa_mkt',
    phone: '089-888-9900',
    status: 'resolved',
    assignedTo: 'tm-2',
    assignedMemberName: 'กานดา สุขสมบูรณ์ (ช่างกาน)',
    createdAt: '2026-10-03T10:00:00.000Z',
    updatedAt: '2026-10-03T11:15:00.000Z',
    resolvedAt: '2026-10-03T11:15:00.000Z',
    solutionNotes: 'รีเซ็ตรหัสผ่านชั่วคราวและส่ง SMS ให้ผู้ขอ พร้อมเพิ่มสิทธิ์ลงใน AD Security Group การตลาด',
    rating: 5,
    customerFeedback: 'จัดการรวดเร็ว ใช้งานได้ตามปกติค่ะ ขอบคุณค่ะ',
    timeline: [
      {
        id: 'tl-10',
        status: 'pending',
        note: 'บันทึกคำขอสิทธิ์ใหม่',
        updatedBy: 'พิมพา นวรัตน์',
        timestamp: '2026-10-03T10:00:00.000Z',
      },
      {
        id: 'tl-11',
        status: 'resolved',
        note: 'อนุมัติและตั้งค่าสิทธิ์เรียบร้อย',
        updatedBy: 'กานดา สุขสมบูรณ์',
        timestamp: '2026-10-03T11:15:00.000Z',
      },
    ],
  },
  {
    id: 'TK-2610-005',
    reporterName: 'อัครพล เกียรติสกุล',
    categoryId: 'cat-hardware',
    categoryName: 'อุปกรณ์และคอมพิวเตอร์ชำรุด',
    description: 'หน้าจอคอมพิวเตอร์เครื่องที่ 4 กระพริบตลอดเวลา สายต่อ HDMI อาจจะหลวมหรือการ์ดจอมีปัญหา',
    priority: 'normal',
    images: [],
    lineContact: 'akkra_k',
    phone: '083-444-5566',
    status: 'pending',
    createdAt: '2026-10-05T14:15:00.000Z',
    updatedAt: '2026-10-05T14:15:00.000Z',
    timeline: [
      {
        id: 'tl-12',
        status: 'pending',
        note: 'เคสถูกบันทึกเข้าระบบ รอหัวหน้าทีมมอบหมายช่าง',
        updatedBy: 'ระบบอัตโนมัติ',
        timestamp: '2026-10-05T14:15:00.000Z',
      },
    ],
  },
  // Previous month data for monthly comparison
  {
    id: 'TK-2609-088',
    reporterName: 'จิราพร พรหมประสิทธิ์',
    categoryId: 'cat-software',
    categoryName: 'ระบบโปรแกรมและซอฟต์แวร์',
    description: 'โปรแกรมสต็อกคำนวณยอดขายผิดพลาดในรอบเดือนกันยายน',
    priority: 'urgent',
    images: [],
    lineContact: 'jiraporn_st',
    status: 'resolved',
    assignedTo: 'tm-2',
    assignedMemberName: 'กานดา สุขสมบูรณ์ (ช่างกาน)',
    createdAt: '2026-09-28T09:00:00.000Z',
    updatedAt: '2026-09-28T14:00:00.000Z',
    resolvedAt: '2026-09-28T14:00:00.000Z',
    solutionNotes: 'ปรับสูตร rounding ใน Stored Procedure และรัน Re-calculate ยอดถูกต้อง',
    rating: 5,
    timeline: [
      {
        id: 'tl-13',
        status: 'resolved',
        note: 'ปิดเคสเรียบร้อย',
        updatedBy: 'กานดา สุขสมบูรณ์',
        timestamp: '2026-09-28T14:00:00.000Z',
      },
    ],
  },
  {
    id: 'TK-2609-075',
    reporterName: 'ณรงค์เดช นามสมมุติ',
    categoryId: 'cat-network',
    categoryName: 'ปัญหาอินเทอร์เน็ตและเครือข่าย',
    description: 'อินเทอร์เน็ตหลุดทั้งแผนกจัดซื้อ สายแลนต้นทางหลวม',
    priority: 'urgent_highest',
    images: [],
    lineContact: 'narongdech',
    status: 'resolved',
    assignedTo: 'tm-1',
    assignedMemberName: 'วิชาญ ชัยมงคล (ช่างวิชาญ)',
    createdAt: '2026-09-20T11:00:00.000Z',
    updatedAt: '2026-09-20T12:30:00.000Z',
    resolvedAt: '2026-09-20T12:30:00.000Z',
    solutionNotes: 'เข้าหัว RJ45 ใหม่ และต่อเข้า Patch Panel แน่นหนา',
    rating: 4,
    timeline: [
      {
        id: 'tl-14',
        status: 'resolved',
        note: 'ปิดเคสเรียบร้อย',
        updatedBy: 'วิชาญ ชัยมงคล',
        timestamp: '2026-09-20T12:30:00.000Z',
      },
    ],
  },
];

export const INITIAL_LINE_SETTINGS: LineSettings = {
  enabled: true,
  notifyToken: '', // User can provide their token or webhook
  webhookUrl: '',
  adminGroupNotify: true,
  statusUpdateNotify: true,
  autoWeeklyReport: true,
};

export const INITIAL_SUPABASE_CONFIG: SupabaseConfig = {
  url: '',
  anonKey: '',
  isConnected: false,
};
